#!/bin/bash
## aws-dropbox
## version 0.0.1 - initial
##################################################
. ${SH2}/cecho.sh
. ${SH2}/aliases/commands.sh
. ${SH2}/build.sh
rate-s3() {
  echo 0.025
}
rate-glacier() {
  echo 0.005
}
rate() {
  commands
}
template-cost-summary() {
  cat << EOF
MONTHLY COST
all in s3: ${cost_monthly_s3} USD/Mo
all in glacier: ${cost_monthly_glacier} USD/Mo
hybrid: ${cost_monthly_hybrid} USD/Mo

YEARLY COST
all in s3: ${cost_yearly_s3} USD/Yr
all in glacier: ${cost_yearly_glacier} USD/Yr
hybrid: ${cost_yearly_hybrid} USD/Yr
EOF
}
template() {
  commands
}
aws-dropbox-main() {
  local candidate_storage
  local -i storage
  read -p "How much space do you need? " candidate_storage
  storage=$(
  case ${candidate_storage} in
   *T) echo $((${candidate_storage//T/}*1024)) ;;
   *G) echo $((${candidate_storage//G/}*1)) ;;
   *)  echo 0
  esac
  )
  test ! ${storage} -gt 0 && return
  echo ok
  cost_monthly_s3=$( gawk "BEGIN { print ${storage} * $( rate s3 ) }" )
  cost_monthly_glacier=$( gawk "BEGIN { print ${storage} * $( rate glacier ) }" )
  cost_monthly_hybrid=$( gawk "BEGIN { print .80 * ${storage} * $( rate s3 ) + .20 * ${storage} * $( rate glacier ) }" )
  cost_yearly_s3=$( gawk "BEGIN { print 12 * ${cost_monthly_s3} }" )
  cost_yearly_glacier=$( gawk "BEGIN { print 12 * ${cost_monthly_glacier} }" )
  cost_yearly_hybrid=$( gawk "BEGIN { print 12 * ${cost_monthly_hybrid} }" )
  template cost-summary
}
aws-dropbox-build() {
  build=build
  build true
}
aws-dropbox-true() {
  true
}
aws-dropbox() {
  commands
}
##################################################
if [ ! ] 
then
 true
else
 exit 1 # wrong args
fi
##################################################
aws-dropbox ${@}
##################################################
## generated by create-stub2.sh v0.1.2
## on Mon, 14 Oct 2019 08:24:43 +0900
## see <https://github.com/temptemp3/sh2>
##################################################
